package dataviewer2;

import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import edu.du.dudraw.Draw;
import edu.du.dudraw.DrawListener;

/**
 * Main controller class for the DataViewer application.
 * This class coordinates between the Model (DataModel), View (DataRenderer), 
 * and State (DataViewState) following the MVC pattern.
 * 
 * Implements DrawListener to handle user keyboard input.
 */
public class DataViewerApp implements DrawListener {

    // ============================================
    // REFACTORED: Constants moved to appropriate classes
    // ============================================
    private final static String WINDOW_TITLE = "DataViewer Application";
    private final static int WINDOW_WIDTH = 1320;
    private final static int WINDOW_HEIGHT = 720;

    // ============================================
    // REFACTORED: New instance variables for MVC pattern
    // ============================================
    private DataModel m_model;
    private DataViewState m_viewState;
    private DataRenderer m_renderer;
    private Draw m_window;
    
    // The current plot data (generated by model when needed)
    private PlotData m_plotData = null;

    /**
     * Constructor sets up the application following MVC pattern.
     * Creates Model, View, and State objects, loads data, and initializes the window.
     * 
     * @param dataFile The path to the CSV data file to load
     * @throws FileNotFoundException if the data file cannot be found
     */
    public DataViewerApp(String dataFile) throws FileNotFoundException {
        // REFACTORED: Create the Model, View, and State
        m_model = new DataModel(dataFile);
        m_viewState = new DataViewState();
        m_renderer = new DataRenderer();

        // REFACTORED: Load data through the model
        m_model.loadData();

        // REFACTORED: Initialize view state with data from model
        if (!m_model.getStates().isEmpty()) {
            m_viewState.setSelectedState(m_model.getStates().first());
        }
        if (!m_model.getYears().isEmpty()) {
            m_viewState.setSelectedStartYear(m_model.getYears().first());
            m_viewState.setSelectedEndYear(m_model.getYears().last());
        }

        // Setup the DuDraw window
        m_window = new Draw(WINDOW_TITLE);
        m_window.setCanvasSize(WINDOW_WIDTH, WINDOW_HEIGHT);
        m_window.enableDoubleBuffering();

        // Add this as the listener for keyboard events
        m_window.addListener(this);

        // Draw the screen for the first time (main menu)
        update();
    }

    /**
     * Updates the display based on current GUI mode.
     * REFACTORED: Now delegates to DataRenderer instead of drawing directly.
     */
    private void update() {
        // REFACTORED: Check state to determine which view to render
        if (m_viewState.getGuiMode() == DataViewState.GUI_MODE_MAIN_MENU) {
            m_renderer.drawMainMenu(m_window, m_viewState);
        } else if (m_viewState.getGuiMode() == DataViewState.GUI_MODE_DATA) {
            // REFACTORED: Pass plot data to renderer
            if (m_plotData != null) {
                m_renderer.drawPlotData(m_window, m_viewState, m_plotData);
            }
        }
        m_window.show();
    }

    // ============================================
    // DrawListener Interface Implementation
    // ============================================

    /**
     * Handles keyboard input from the user.
     * REFACTORED: Now uses DataViewState for all state management
     * and delegates to DataModel and DataRenderer as appropriate.
     */
    @Override
    public void keyPressed(int key) {
        boolean needsUpdate = false;
        boolean needsUpdatePlotData = false;

        // Handle quit from any mode
        if (key == 'Q') {
            System.out.println("INFO: User quit the application");
            System.exit(0);
        }

        // REFACTORED: Use viewState to check current mode
        if (m_viewState.getGuiMode() == DataViewState.GUI_MODE_MAIN_MENU) {
            
            if (key == 'C') {
                // Set the country
                Object selectedValue = JOptionPane.showInputDialog(
                    null,
                    "Choose the country",
                    "Input",
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    m_model.getCountries().toArray(),
                    m_viewState.getSelectedCountry()
                );
                
                if (selectedValue != null) {
                    System.out.println(String.format("INFO: User selected: '%s'", selectedValue));
                    String country = (String) selectedValue;
                    
                    // REFACTORED: Update state through setter
                    if (!m_viewState.getSelectedCountry().equals(country)) {
                        m_viewState.setSelectedCountry(country);
                        
                        // Reload data for new country
                        try {
                            m_model.loadData();
                            
                            // Update state with new data bounds
                            if (!m_model.getStates().isEmpty()) {
                                m_viewState.setSelectedState(m_model.getStates().first());
                            }
                            if (!m_model.getYears().isEmpty()) {
                                m_viewState.setSelectedStartYear(m_model.getYears().first());
                                m_viewState.setSelectedEndYear(m_model.getYears().last());
                            }
                            
                            needsUpdate = true;
                            needsUpdatePlotData = true;
                        } catch (FileNotFoundException e) {
                            System.err.println("ERROR: Failed to reload data: " + e.getMessage());
                        }
                    }
                }
            } 
            else if (key == 'T') {
                // Set the state/territory
                Object selectedValue = JOptionPane.showInputDialog(
                    null,
                    "Choose the state",
                    "Input",
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    m_model.getStates().toArray(),
                    m_viewState.getSelectedState()
                );
                
                if (selectedValue != null) {
                    System.out.println(String.format("INFO: User selected: '%s'", selectedValue));
                    String state = (String) selectedValue;
                    
                    // REFACTORED: Update state through setter
                    if (!m_viewState.getSelectedState().equals(state)) {
                        m_viewState.setSelectedState(state);
                        needsUpdate = true;
                        needsUpdatePlotData = true;
                    }
                }
            } 
            else if (key == 'P') {
                // Plot the data
                System.out.println("INFO: User selected to plot the data");
                
                // REFACTORED: Change mode through state setter
                m_viewState.setGuiMode(DataViewState.GUI_MODE_DATA);
                needsUpdate = true;
                needsUpdatePlotData = true;
            } 
            else if (key == 'S') {
                // Set start year
                Object selectedValue = JOptionPane.showInputDialog(
                    null,
                    "Choose the start year",
                    "Input",
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    m_model.getYears().toArray(),
                    m_viewState.getSelectedStartYear()
                );
                
                if (selectedValue != null) {
                    System.out.println(String.format("INFO: User selected: '%s'", selectedValue));
                    Integer year = (Integer) selectedValue;
                    
                    // Validate start year is not after end year
                    if (year.compareTo(m_viewState.getSelectedEndYear()) > 0) {
                        System.err.println(String.format(
                            "ERROR: new start year (%d) must not be after end year (%d)",
                            year,
                            m_viewState.getSelectedEndYear()
                        ));
                    } else {
                        // REFACTORED: Update through setter
                        if (!m_viewState.getSelectedStartYear().equals(year)) {
                            m_viewState.setSelectedStartYear(year);
                            needsUpdate = true;
                            needsUpdatePlotData = true;
                        }
                    }
                }
            } 
            else if (key == 'E') {
                // Set end year
                Object selectedValue = JOptionPane.showInputDialog(
                    null,
                    "Choose the end year",
                    "Input",
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    m_model.getYears().toArray(),
                    m_viewState.getSelectedEndYear()
                );
                
                if (selectedValue != null) {
                    System.out.println(String.format("INFO: User selected: '%s'", selectedValue));
                    Integer year = (Integer) selectedValue;
                    
                    // Validate end year is not before start year
                    if (year.compareTo(m_viewState.getSelectedStartYear()) < 0) {
                        System.err.println(String.format(
                            "ERROR: new end year (%d) must not be before start year (%d)",
                            year,
                            m_viewState.getSelectedStartYear()
                        ));
                    } else {
                        // REFACTORED: Update through setter
                        if (!m_viewState.getSelectedEndYear().equals(year)) {
                            m_viewState.setSelectedEndYear(year);
                            needsUpdate = true;
                            needsUpdatePlotData = true;
                        }
                    }
                }
            } 
            else if (key == 'V') {
                // Set visualization mode
                Object selectedValue = JOptionPane.showInputDialog(
                    null,
                    "Choose the visualization mode",
                    "Input",
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    DataViewState.VISUALIZATION_MODES,
                    m_viewState.getSelectedVisualization()
                );
                
                if (selectedValue != null) {
                    System.out.println(String.format("INFO: User selected: '%s'", selectedValue));
                    String visualization = (String) selectedValue;
                    
                    // REFACTORED: Update through setter
                    if (!m_viewState.getSelectedVisualization().equals(visualization)) {
                        m_viewState.setSelectedVisualization(visualization);
                        needsUpdate = true;
                    }
                }
            }
        } 
        else if (m_viewState.getGuiMode() == DataViewState.GUI_MODE_DATA) {
            // In plot data view
            if (key == 'M') {
                // Return to main menu
                System.out.println("INFO: User returned to main menu");
                m_viewState.setGuiMode(DataViewState.GUI_MODE_MAIN_MENU);
                needsUpdate = true;
            }
        } 
        else {
            throw new IllegalStateException(
                String.format("Unexpected GUI mode: %d", m_viewState.getGuiMode())
            );
        }

        // REFACTORED: Generate plot data through model if needed
        if (needsUpdatePlotData) {
            m_plotData = m_model.generatePlotData(m_viewState);
        }

        // REFACTORED: Update display through renderer if needed
        if (needsUpdate) {
            update();
        }
    }

    @Override
    public void keyReleased(int key) {
        // Not used
    }

    @Override
    public void keyTyped(char key) {
        // Not used
    }

    @Override
    public void mouseClicked(double x, double y) {
        // Not used
    }

    @Override
    public void mouseDragged(double x, double y) {
        // Not used
    }

    @Override
    public void mousePressed(double x, double y) {
        // Not used
    }

    @Override
    public void mouseReleased(double x, double y) {
        // Not used
    }
}
